<?xml version="1.0" encoding="utf-8"?><Database Name="CompetitionsDB" Class="CompetitionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=V-ПК;Initial Catalog=CompetitionsDB;User ID=Potapov" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CompetitionsDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UsersTable" Member="UsersTable">
    <Type Name="UsersTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UsersTable_zApplicationTable" Member="zApplicationTables" ThisKey="ID" OtherKey="FK_UsersTable" Type="zApplicationTable" />
      <Association Name="UsersTable_zExpertsAndApplicationMappingTable" Member="zExpertsAndApplicationMappingTables" ThisKey="ID" OtherKey="FK_UsersTable" Type="zExpertsAndApplicationMappingTable" />
      <Association Name="UsersTable_zExpertPointsValue" Member="zExpertPointsValues" ThisKey="ID" OtherKey="FK_ExpertsTable" Type="zExpertPointsValue" />
    </Type>
  </Table>
  <Table Name="dbo.zSectionTable" Member="zSectionTable">
    <Type Name="zSectionTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FK_CompetitionsTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ColumnMaxCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="zSectionTable_zCollectedRowsTable" Member="zCollectedRowsTable" ThisKey="ID" OtherKey="FK_SectionTable" Type="zCollectedRowsTable" />
      <Association Name="zSectionTable_zColumnTable" Member="zColumnTable" ThisKey="ID" OtherKey="FK_SectionTable" Type="zColumnTable" />
      <Association Name="zCompetitionsTable_zSectionTable" Member="zCompetitionsTable" ThisKey="FK_CompetitionsTable" OtherKey="ID" Type="zCompetitionsTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zCollectedDataTable" Member="zCollectedDataTable">
    <Type Name="zCollectedDataTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastChangeDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FK_ColumnTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_CollectedRowsTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ConstantListTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValueText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ValueDouble" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ValueInt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValueBit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ValueFK_CollectedDataTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValueDataTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="zCollectedDataTable_zCollectedDataTable" Member="zCollectedDataTable2" ThisKey="ID" OtherKey="ValueFK_CollectedDataTable" Type="zCollectedDataTable" />
      <Association Name="zCollectedDataTable_zCollectedDataTable" Member="zCollectedDataTable1" ThisKey="ValueFK_CollectedDataTable" OtherKey="ID" Type="zCollectedDataTable" IsForeignKey="true" />
      <Association Name="zCollectedRowsTable_zCollectedDataTable" Member="zCollectedRowsTable" ThisKey="FK_CollectedRowsTable" OtherKey="ID" Type="zCollectedRowsTable" IsForeignKey="true" />
      <Association Name="zColumnTable_zCollectedDataTable" Member="zColumnTable" ThisKey="FK_ColumnTable" OtherKey="ID" Type="zColumnTable" IsForeignKey="true" />
      <Association Name="zConstantListTable_zCollectedDataTable" Member="zConstantListTable" ThisKey="FK_ConstantListTable" OtherKey="ID" Type="zConstantListTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zCollectedRowsTable" Member="zCollectedRowsTable">
    <Type Name="zCollectedRowsTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FK_SectionTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_ApplicationTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="zCollectedRowsTable_zCollectedDataTable" Member="zCollectedDataTable" ThisKey="ID" OtherKey="FK_CollectedRowsTable" Type="zCollectedDataTable" />
      <Association Name="zSectionTable_zCollectedRowsTable" Member="zSectionTable" ThisKey="FK_SectionTable" OtherKey="ID" Type="zSectionTable" IsForeignKey="true" />
      <Association Name="zApplicationTable_zCollectedRowsTable" Member="zApplicationTable" ThisKey="FK_ApplicationTable" OtherKey="ID" Type="zApplicationTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zColumnTable" Member="zColumnTable">
    <Type Name="zColumnTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FK_SectionTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_ColumnTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ConstantListsTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="zColumnTable_zCollectedDataTable" Member="zCollectedDataTable" ThisKey="ID" OtherKey="FK_ColumnTable" Type="zCollectedDataTable" />
      <Association Name="zColumnTable_zColumnTable" Member="zColumnTable2" ThisKey="ID" OtherKey="FK_ColumnTable" Type="zColumnTable" />
      <Association Name="zColumnTable_zColumnTable" Member="zColumnTable1" ThisKey="FK_ColumnTable" OtherKey="ID" Type="zColumnTable" IsForeignKey="true" />
      <Association Name="zSectionTable_zColumnTable" Member="zSectionTable" ThisKey="FK_SectionTable" OtherKey="ID" Type="zSectionTable" IsForeignKey="true" />
      <Association Name="zConstantListTable_zColumnTable" Member="zConstantListTable" ThisKey="FK_ConstantListsTable" OtherKey="ID" Type="zConstantListTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zConstantListTable" Member="zConstantListTable">
    <Type Name="zConstantListTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="FK_CompetitionTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="zConstantListTable_zCollectedDataTable" Member="zCollectedDataTable" ThisKey="ID" OtherKey="FK_ConstantListTable" Type="zCollectedDataTable" />
      <Association Name="zConstantListTable_zColumnTable" Member="zColumnTable" ThisKey="ID" OtherKey="FK_ConstantListsTable" Type="zColumnTable" />
      <Association Name="zCompetitionsTable_zConstantListTable" Member="zCompetitionsTable" ThisKey="FK_CompetitionTable" OtherKey="ID" Type="zCompetitionsTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zApplicationTable" Member="zApplicationTables">
    <Type Name="zApplicationTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_UsersTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_CompetitionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CretaDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Sended" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="zApplicationTable_zCollectedRowsTable" Member="zCollectedRowsTables" ThisKey="ID" OtherKey="FK_ApplicationTable" Type="zCollectedRowsTable" />
      <Association Name="zApplicationTable_zExpertsAndApplicationMappingTable" Member="zExpertsAndApplicationMappingTables" ThisKey="ID" OtherKey="FK_ApplicationsTable" Type="zExpertsAndApplicationMappingTable" />
      <Association Name="zApplicationTable_zExpertPointsValue" Member="zExpertPointsValues" ThisKey="ID" OtherKey="FK_ApplicationTable" Type="zExpertPointsValue" />
      <Association Name="UsersTable_zApplicationTable" Member="UsersTable" ThisKey="FK_UsersTable" OtherKey="ID" Type="UsersTable" IsForeignKey="true" />
      <Association Name="zCompetitionsTable_zApplicationTable" Member="zCompetitionsTable" ThisKey="FK_CompetitionTable" OtherKey="ID" Type="zCompetitionsTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zCompetitionsTable" Member="zCompetitionsTables">
    <Type Name="zCompetitionsTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="OpenForApplications" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TemplateDocName" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="zCompetitionsTable_zSectionTable" Member="zSectionTables" ThisKey="ID" OtherKey="FK_CompetitionsTable" Type="zSectionTable" />
      <Association Name="zCompetitionsTable_zConstantListTable" Member="zConstantListTables" ThisKey="ID" OtherKey="FK_CompetitionTable" Type="zConstantListTable" />
      <Association Name="zCompetitionsTable_zApplicationTable" Member="zApplicationTables" ThisKey="ID" OtherKey="FK_CompetitionTable" Type="zApplicationTable" />
    </Type>
  </Table>
  <Table Name="dbo.zExpertsAndApplicationMappingTable" Member="zExpertsAndApplicationMappingTables">
    <Type Name="zExpertsAndApplicationMappingTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_UsersTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ApplicationsTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UsersTable_zExpertsAndApplicationMappingTable" Member="UsersTable" ThisKey="FK_UsersTable" OtherKey="ID" Type="UsersTable" IsForeignKey="true" />
      <Association Name="zApplicationTable_zExpertsAndApplicationMappingTable" Member="zApplicationTable" ThisKey="FK_ApplicationsTable" OtherKey="ID" Type="zApplicationTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zExpertPoints" Member="zExpertPoints">
    <Type Name="zExpertPoint">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MinValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="zExpertPoint_zExpertPointsValue" Member="zExpertPointsValues" ThisKey="ID" OtherKey="FK_ExpertsTable" Type="zExpertPointsValue" />
    </Type>
  </Table>
  <Table Name="dbo.zExpertPointsValue" Member="zExpertPointsValues">
    <Type Name="zExpertPointsValue">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FK_ExpertsTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ApplicationTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ExpertPoints" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastChangeDataTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UsersTable_zExpertPointsValue" Member="UsersTable" ThisKey="FK_ExpertsTable" OtherKey="ID" Type="UsersTable" IsForeignKey="true" />
      <Association Name="zApplicationTable_zExpertPointsValue" Member="zApplicationTable" ThisKey="FK_ApplicationTable" OtherKey="ID" Type="zApplicationTable" IsForeignKey="true" />
      <Association Name="zExpertPoint_zExpertPointsValue" Member="zExpertPoint" ThisKey="FK_ExpertsTable" OtherKey="ID" Type="zExpertPoint" IsForeignKey="true" />
    </Type>
  </Table>
</Database>