<?xml version="1.0" encoding="utf-8"?><Database Name="RankDB" Class="UsersDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-QB5CCK4;Initial Catalog=RankDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Release_ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmailCopies" Member="EmailCopies">
    <Type Name="EmailCopies">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailTo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailFrom" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailTitle" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailContent" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EmailAttachment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SendDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SendOk" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.EmailSendTable" Member="EmailSendTable">
    <Type Name="EmailSendTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SMTPName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SendOk" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SendError" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmailTemplate" Member="EmailTemplate">
    <Type Name="EmailTemplate">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="EmailTitle" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EmailContent" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NameRus" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FirstLevelSubdivisionTable" Member="FirstLevelSubdivisionTable">
    <Type Name="FirstLevelSubdivisionTable">
      <Column Name="FirstLevelSubdivisionTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AbbRu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="FirstLevelSubdivisionTable_Rank_StructPoints" Member="Rank_StructPoints" ThisKey="FirstLevelSubdivisionTableID" OtherKey="FK_firstlvl" Type="Rank_StructPoints" />
      <Association Name="FirstLevelSubdivisionTable_SecondLevelSubdivisionTable" Member="SecondLevelSubdivisionTable" ThisKey="FirstLevelSubdivisionTableID" OtherKey="FK_FirstLevelSubdivisionTable" Type="SecondLevelSubdivisionTable" />
      <Association Name="FirstLevelSubdivisionTable_UsersTable" Member="UsersTable" ThisKey="FirstLevelSubdivisionTableID" OtherKey="FK_FirstLevelSubdivisionTable" Type="UsersTable" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_Articles" Member="Rank_Articles">
    <Type Name="Rank_Articles">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_parametr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AddDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rank_Articles_Rank_ArticleValues" Member="Rank_ArticleValues" ThisKey="ID" OtherKey="FK_Article" Type="Rank_ArticleValues" />
      <Association Name="Rank_Articles_Rank_NotSystemAuthors" Member="Rank_NotSystemAuthors" ThisKey="ID" OtherKey="FK_Article" Type="Rank_NotSystemAuthors" />
      <Association Name="Rank_Articles_Rank_UserArticleMappingTable" Member="Rank_UserArticleMappingTable" ThisKey="ID" OtherKey="FK_Article" Type="Rank_UserArticleMappingTable" />
      <Association Name="Rank_Mark_Rank_Articles" Member="Rank_Mark" ThisKey="FK_mark" OtherKey="ID" Type="Rank_Mark" IsForeignKey="true" />
      <Association Name="Rank_Parametrs_Rank_Articles" Member="Rank_Parametrs" ThisKey="FK_parametr" OtherKey="ID" Type="Rank_Parametrs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_ArticleValues" Member="Rank_ArticleValues">
    <Type Name="Rank_ArticleValues">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Article" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Field" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_Param" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rank_Articles_Rank_ArticleValues" Member="Rank_Articles" ThisKey="FK_Article" OtherKey="ID" Type="Rank_Articles" IsForeignKey="true" />
      <Association Name="Rank_Fields_Rank_ArticleValues" Member="Rank_Fields" ThisKey="FK_Field" OtherKey="ID" Type="Rank_Fields" IsForeignKey="true" />
      <Association Name="Rank_Parametrs_Rank_ArticleValues" Member="Rank_Parametrs" ThisKey="FK_Param" OtherKey="ID" Type="Rank_Parametrs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_DifficaltPoint" Member="Rank_DifficaltPoint">
    <Type Name="Rank_DifficaltPoint">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fk_parametr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rank_DifficaltPoint_Rank_NotSystemAuthors" Member="Rank_NotSystemAuthors" ThisKey="ID" OtherKey="FK_Point" Type="Rank_NotSystemAuthors" />
      <Association Name="Rank_DifficaltPoint_Rank_UserArticleMappingTable" Member="Rank_UserArticleMappingTable" ThisKey="ID" OtherKey="FK_point" Type="Rank_UserArticleMappingTable" />
      <Association Name="Rank_Parametrs_Rank_DifficaltPoint" Member="Rank_Parametrs" ThisKey="fk_parametr" OtherKey="ID" Type="Rank_Parametrs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_DropDown" Member="Rank_DropDown">
    <Type Name="Rank_DropDown">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DropDown" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Rank_DropDown_Rank_DropDownValues" Member="Rank_DropDownValues" ThisKey="ID" OtherKey="FK_dropdown" Type="Rank_DropDownValues" />
      <Association Name="Rank_DropDown_Rank_Fields" Member="Rank_Fields" ThisKey="ID" OtherKey="FK_dropdown" Type="Rank_Fields" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_DropDownValues" Member="Rank_DropDownValues">
    <Type Name="Rank_DropDownValues">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_dropdown" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FloatValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Rank_DropDown_Rank_DropDownValues" Member="Rank_DropDown" ThisKey="FK_dropdown" OtherKey="ID" Type="Rank_DropDown" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_Fields" Member="Rank_Fields">
    <Type Name="Rank_Fields">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FK_parametr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="line" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="col" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="step" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="high" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="FK_dropdown" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="formtype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rank_Fields_Rank_ArticleValues" Member="Rank_ArticleValues" ThisKey="ID" OtherKey="FK_Field" Type="Rank_ArticleValues" />
      <Association Name="Rank_DropDown_Rank_Fields" Member="Rank_DropDown" ThisKey="FK_dropdown" OtherKey="ID" Type="Rank_DropDown" IsForeignKey="true" />
      <Association Name="Rank_Mark_Rank_Fields" Member="Rank_Mark" ThisKey="FK_mark" OtherKey="ID" Type="Rank_Mark" IsForeignKey="true" />
      <Association Name="Rank_Parametrs_Rank_Fields" Member="Rank_Parametrs" ThisKey="FK_parametr" OtherKey="ID" Type="Rank_Parametrs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_Mark" Member="Rank_Mark">
    <Type Name="Rank_Mark">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Points" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fk_parametr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rank_Mark_Rank_Articles" Member="Rank_Articles" ThisKey="ID" OtherKey="FK_mark" Type="Rank_Articles" />
      <Association Name="Rank_Mark_Rank_Fields" Member="Rank_Fields" ThisKey="ID" OtherKey="FK_mark" Type="Rank_Fields" />
      <Association Name="Rank_Parametrs_Rank_Mark" Member="Rank_Parametrs" ThisKey="fk_parametr" OtherKey="ID" Type="Rank_Parametrs" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_NotSystemAuthors" Member="Rank_NotSystemAuthors">
    <Type Name="Rank_NotSystemAuthors">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FIO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Article" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rank_Articles_Rank_NotSystemAuthors" Member="Rank_Articles" ThisKey="FK_Article" OtherKey="ID" Type="Rank_Articles" IsForeignKey="true" />
      <Association Name="Rank_DifficaltPoint_Rank_NotSystemAuthors" Member="Rank_DifficaltPoint" ThisKey="FK_Point" OtherKey="ID" Type="Rank_DifficaltPoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_Parametrs" Member="Rank_Parametrs">
    <Type Name="Rank_Parametrs">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EditUserType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OneOrManyAuthor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rank_Parametrs_Rank_Articles" Member="Rank_Articles" ThisKey="ID" OtherKey="FK_parametr" Type="Rank_Articles" />
      <Association Name="Rank_Parametrs_Rank_ArticleValues" Member="Rank_ArticleValues" ThisKey="ID" OtherKey="FK_Param" Type="Rank_ArticleValues" />
      <Association Name="Rank_Parametrs_Rank_DifficaltPoint" Member="Rank_DifficaltPoint" ThisKey="ID" OtherKey="fk_parametr" Type="Rank_DifficaltPoint" />
      <Association Name="Rank_Parametrs_Rank_Fields" Member="Rank_Fields" ThisKey="ID" OtherKey="FK_parametr" Type="Rank_Fields" />
      <Association Name="Rank_Parametrs_Rank_Mark" Member="Rank_Mark" ThisKey="ID" OtherKey="fk_parametr" Type="Rank_Mark" />
      <Association Name="Rank_Parametrs_Rank_UserParametrValue" Member="Rank_UserParametrValue" ThisKey="ID" OtherKey="FK_parametr" Type="Rank_UserParametrValue" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_StructPoints" Member="Rank_StructPoints">
    <Type Name="Rank_StructPoints">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_thirdlvl" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_secondlvl" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_firstlvl" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="FirstLevelSubdivisionTable_Rank_StructPoints" Member="FirstLevelSubdivisionTable" ThisKey="FK_firstlvl" OtherKey="FirstLevelSubdivisionTableID" Type="FirstLevelSubdivisionTable" IsForeignKey="true" />
      <Association Name="SecondLevelSubdivisionTable_Rank_StructPoints" Member="SecondLevelSubdivisionTable" ThisKey="FK_secondlvl" OtherKey="SecondLevelSubdivisionTableID" Type="SecondLevelSubdivisionTable" IsForeignKey="true" />
      <Association Name="ThirdLevelSubdivisionTable_Rank_StructPoints" Member="ThirdLevelSubdivisionTable" ThisKey="FK_thirdlvl" OtherKey="ThirdLevelSubdivisionTableID" Type="ThirdLevelSubdivisionTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_UserArticleMappingTable" Member="Rank_UserArticleMappingTable">
    <Type Name="Rank_UserArticleMappingTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Article" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserConfirm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ValuebyArticle" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Rank_Articles_Rank_UserArticleMappingTable" Member="Rank_Articles" ThisKey="FK_Article" OtherKey="ID" Type="Rank_Articles" IsForeignKey="true" />
      <Association Name="Rank_DifficaltPoint_Rank_UserArticleMappingTable" Member="Rank_DifficaltPoint" ThisKey="FK_point" OtherKey="ID" Type="Rank_DifficaltPoint" IsForeignKey="true" />
      <Association Name="UsersTable_Rank_UserArticleMappingTable" Member="UsersTable" ThisKey="FK_User" OtherKey="UsersTableID" Type="UsersTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_UserParametrValue" Member="Rank_UserParametrValue">
    <Type Name="Rank_UserParametrValue">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_parametr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AcceptDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Accept" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Rank_Parametrs_Rank_UserParametrValue" Member="Rank_Parametrs" ThisKey="FK_parametr" OtherKey="ID" Type="Rank_Parametrs" IsForeignKey="true" />
      <Association Name="UsersTable_Rank_UserParametrValue" Member="UsersTable" ThisKey="FK_user" OtherKey="UsersTableID" Type="UsersTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rank_UserRatingPoints" Member="Rank_UserRatingPoints">
    <Type Name="Rank_UserRatingPoints">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="UsersTable_Rank_UserRatingPoints" Member="UsersTable" ThisKey="FK_User" OtherKey="UsersTableID" Type="UsersTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SecondLevelSubdivisionTable" Member="SecondLevelSubdivisionTable">
    <Type Name="SecondLevelSubdivisionTable">
      <Column Name="SecondLevelSubdivisionTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FK_FirstLevelSubdivisionTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SecondLevelSubdivisionTable_Rank_StructPoints" Member="Rank_StructPoints" ThisKey="SecondLevelSubdivisionTableID" OtherKey="FK_secondlvl" Type="Rank_StructPoints" />
      <Association Name="SecondLevelSubdivisionTable_ThirdLevelSubdivisionTable" Member="ThirdLevelSubdivisionTable" ThisKey="SecondLevelSubdivisionTableID" OtherKey="FK_SecondLevelSubdivisionTable" Type="ThirdLevelSubdivisionTable" />
      <Association Name="SecondLevelSubdivisionTable_UsersTable" Member="UsersTable" ThisKey="SecondLevelSubdivisionTableID" OtherKey="FK_SecondLevelSubdivisionTable" Type="UsersTable" />
      <Association Name="FirstLevelSubdivisionTable_SecondLevelSubdivisionTable" Member="FirstLevelSubdivisionTable" ThisKey="FK_FirstLevelSubdivisionTable" OtherKey="FirstLevelSubdivisionTableID" Type="FirstLevelSubdivisionTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThirdLevelSubdivisionTable" Member="ThirdLevelSubdivisionTable">
    <Type Name="ThirdLevelSubdivisionTable">
      <Column Name="ThirdLevelSubdivisionTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FK_SecondLevelSubdivisionTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ThirdLevelSubdivisionTable_Rank_StructPoints" Member="Rank_StructPoints" ThisKey="ThirdLevelSubdivisionTableID" OtherKey="FK_thirdlvl" Type="Rank_StructPoints" />
      <Association Name="ThirdLevelSubdivisionTable_UsersTable" Member="UsersTable" ThisKey="ThirdLevelSubdivisionTableID" OtherKey="FK_ThirdLevelSubdivisionTable" Type="UsersTable" />
      <Association Name="SecondLevelSubdivisionTable_ThirdLevelSubdivisionTable" Member="SecondLevelSubdivisionTable" ThisKey="FK_SecondLevelSubdivisionTable" OtherKey="SecondLevelSubdivisionTableID" Type="SecondLevelSubdivisionTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersTable" Member="UsersTable">
    <Type Name="UsersTable">
      <Column Name="UsersTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Patronimyc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FK_FirstLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_SecondLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ThirdLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PassCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Confirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Stavka" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Degree" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PublicationFIO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TypeOfPosition" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="UsersTable_Rank_UserArticleMappingTable" Member="Rank_UserArticleMappingTable" ThisKey="UsersTableID" OtherKey="FK_User" Type="Rank_UserArticleMappingTable" />
      <Association Name="UsersTable_Rank_UserParametrValue" Member="Rank_UserParametrValue" ThisKey="UsersTableID" OtherKey="FK_user" Type="Rank_UserParametrValue" />
      <Association Name="UsersTable_Rank_UserRatingPoints" Member="Rank_UserRatingPoints" ThisKey="UsersTableID" OtherKey="FK_User" Type="Rank_UserRatingPoints" />
      <Association Name="FirstLevelSubdivisionTable_UsersTable" Member="FirstLevelSubdivisionTable" ThisKey="FK_FirstLevelSubdivisionTable" OtherKey="FirstLevelSubdivisionTableID" Type="FirstLevelSubdivisionTable" IsForeignKey="true" />
      <Association Name="SecondLevelSubdivisionTable_UsersTable" Member="SecondLevelSubdivisionTable" ThisKey="FK_SecondLevelSubdivisionTable" OtherKey="SecondLevelSubdivisionTableID" Type="SecondLevelSubdivisionTable" IsForeignKey="true" />
      <Association Name="ThirdLevelSubdivisionTable_UsersTable" Member="ThirdLevelSubdivisionTable" ThisKey="FK_ThirdLevelSubdivisionTable" OtherKey="ThirdLevelSubdivisionTableID" Type="ThirdLevelSubdivisionTable" IsForeignKey="true" />
    </Type>
  </Table>
</Database>