<?xml version="1.0" encoding="utf-8"?><Database Name="Konkursy" Class="CompetitionDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=РЕМА-ПК\REMAIDEMBUHAT;Initial Catalog=Konkursy;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KonkursyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Activity" Member="Activity">
    <Type Name="Activity">
      <Column Name="ID_Activity" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Activity" Member="Activity1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PlanDateNull" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bids_Activity" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Answers" Member="Answers">
    <Type Name="Answers">
      <Column Name="ID_Answer" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Answers_Question_AnswerMapingTable" Member="Question_AnswerMapingTable" ThisKey="ID_Answer" OtherKey="FK_Answer" Type="Question_AnswerMapingTable" />
      <Association Name="Bids_Answers" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AutoFilling" Member="AutoFilling">
    <Type Name="AutoFilling">
      <Column Name="ID_Doc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Konkurs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Page" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Konkursy_AutoFilling" Member="Konkursy" ThisKey="FK_Konkurs" OtherKey="ID_Konkurs" Type="Konkursy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bids" Member="Bids">
    <Type Name="Bids">
      <Column Name="ID_Bid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BidName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FK_Konkurs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Coment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Bids_Activity" Member="Activity" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="Activity" />
      <Association Name="Bids_Answers" Member="Answers" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="Answers" />
      <Association Name="Bids_CalendarPlan" Member="CalendarPlan" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="CalendarPlan" />
      <Association Name="Bids_Indicators" Member="Indicators" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="Indicators" />
      <Association Name="Bids_PurchasePlan" Member="PurchasePlan" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="PurchasePlan" />
      <Association Name="Bids_Reports" Member="Reports" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="Reports" />
      <Association Name="Bids_Result" Member="Result" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="Result" />
      <Association Name="Bids_Risks" Member="Risks" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="Risks" />
      <Association Name="Bids_SmetaValue" Member="SmetaValue" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="SmetaValue" />
      <Association Name="Bids_TargetIndicatorValue" Member="TargetIndicatorValue" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="TargetIndicatorValue" />
      <Association Name="Bids_TaskResult" Member="TaskResult" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="TaskResult" />
      <Association Name="Bids_TitleInfo" Member="TitleInfo" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="TitleInfo" />
      <Association Name="Bids_User_BidMapingTable" Member="User_BidMapingTable" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="User_BidMapingTable" />
      <Association Name="Konkursy_Bids" Member="Konkursy" ThisKey="FK_Konkurs" OtherKey="ID_Konkurs" Type="Konkursy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CalendarPlan" Member="CalendarPlan">
    <Type Name="CalendarPlan">
      <Column Name="ID_Event" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Event" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Cost1000" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SourceNull" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TimeNull" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Bids_CalendarPlan" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Indicators" Member="Indicators">
    <Type Name="Indicators">
      <Column Name="ID_Indicator" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Indicator" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PlanDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Bids_Indicators" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Konkurs-QuestionMapingTable]" Member="Konkurs_QuestionMapingTable">
    <Type Name="Konkurs_QuestionMapingTable">
      <Column Name="ID_KonkursQuestion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Konkurs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Konkursy_Konkurs_QuestionMapingTable" Member="Konkursy" ThisKey="FK_Konkurs" OtherKey="ID_Konkurs" Type="Konkursy" IsForeignKey="true" />
      <Association Name="Questions_Konkurs_QuestionMapingTable" Member="Questions" ThisKey="FK_Question" OtherKey="ID_Question" Type="Questions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Konkurs-TargetMapingTable]" Member="Konkurs_TargetMapingTable">
    <Type Name="Konkurs_TargetMapingTable">
      <Column Name="ID_KonkursTarget" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Konkurs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Target" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Konkursy_Konkurs_TargetMapingTable" Member="Konkursy" ThisKey="FK_Konkurs" OtherKey="ID_Konkurs" Type="Konkursy" IsForeignKey="true" />
      <Association Name="TargetIndicators_Konkurs_TargetMapingTable" Member="TargetIndicators" ThisKey="FK_Target" OtherKey="ID_TargetIndicator" Type="TargetIndicators" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Konkursy" Member="Konkursy">
    <Type Name="Konkursy">
      <Column Name="ID_Konkurs" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FK_Curator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Konkursy_AutoFilling" Member="AutoFilling" ThisKey="ID_Konkurs" OtherKey="FK_Konkurs" Type="AutoFilling" />
      <Association Name="Konkursy_Bids" Member="Bids" ThisKey="ID_Konkurs" OtherKey="FK_Konkurs" Type="Bids" />
      <Association Name="Konkursy_Konkurs_QuestionMapingTable" Member="Konkurs_QuestionMapingTable" ThisKey="ID_Konkurs" OtherKey="FK_Konkurs" Type="Konkurs_QuestionMapingTable" />
      <Association Name="Konkursy_Konkurs_TargetMapingTable" Member="Konkurs_TargetMapingTable" ThisKey="ID_Konkurs" OtherKey="FK_Konkurs" Type="Konkurs_TargetMapingTable" />
      <Association Name="Konkursy_Smeta" Member="Smeta" ThisKey="ID_Konkurs" OtherKey="FK_Konkurs" Type="Smeta" />
      <Association Name="Users_Konkursy" Member="Users" ThisKey="FK_Curator" OtherKey="ID_User" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchasePlan" Member="PurchasePlan">
    <Type Name="PurchasePlan">
      <Column Name="ID_Purchase" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Purchase" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Sum" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PurchasePlan_SpecialPart" Member="SpecialPart" ThisKey="ID_Purchase" OtherKey="FK_Purchase" Type="SpecialPart" />
      <Association Name="PurchasePlan_TargetIndicatorValue" Member="TargetIndicatorValue" ThisKey="ID_Purchase" OtherKey="FK_Purchase" Type="TargetIndicatorValue" />
      <Association Name="Bids_PurchasePlan" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Question-AnswerMapingTable]" Member="Question_AnswerMapingTable">
    <Type Name="Question_AnswerMapingTable">
      <Column Name="ID_QuestionAnswer" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Question" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Answer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Answers_Question_AnswerMapingTable" Member="Answers" ThisKey="FK_Answer" OtherKey="ID_Answer" Type="Answers" IsForeignKey="true" />
      <Association Name="Questions_Question_AnswerMapingTable" Member="Questions" ThisKey="FK_Question" OtherKey="ID_Question" Type="Questions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Questions">
      <Column Name="ID_Question" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Uniqvalue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Questions_Konkurs_QuestionMapingTable" Member="Konkurs_QuestionMapingTable" ThisKey="ID_Question" OtherKey="FK_Question" Type="Konkurs_QuestionMapingTable" />
      <Association Name="Questions_Question_AnswerMapingTable" Member="Question_AnswerMapingTable" ThisKey="ID_Question" OtherKey="FK_Question" Type="Question_AnswerMapingTable" />
    </Type>
  </Table>
  <Table Name="dbo.Reports" Member="Reports">
    <Type Name="Reports">
      <Column Name="ID_Report" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Report" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateOSPRNull" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartDateNull" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDateNull" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Bids_Reports" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Result" Member="Result">
    <Type Name="Result">
      <Column Name="ID_Result" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Task" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResultName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ResultType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Claim" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Criteria" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Method" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Responsible" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Result_ResultComent" Member="ResultComent" ThisKey="ID_Result" OtherKey="FK_Result" Type="ResultComent" />
      <Association Name="Bids_Result" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
      <Association Name="TaskResult_Result" Member="TaskResult" ThisKey="FK_Task" OtherKey="ID_Task" Type="TaskResult" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResultComent" Member="ResultComent">
    <Type Name="ResultComent">
      <Column Name="ID_Coment" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Result" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComentText" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Result_ResultComent" Member="Result" ThisKey="FK_Result" OtherKey="ID_Result" Type="Result" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Risks" Member="Risks">
    <Type Name="Risks">
      <Column Name="ID_Risk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RiskName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Effect" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Method" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Reaction" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Bids_Risks" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Smeta" Member="Smeta">
    <Type Name="Smeta">
      <Column Name="ID_State" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name_state" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Type_state" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Uniqvalue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_Konkurs" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Smeta_SmetaValue" Member="SmetaValue" ThisKey="ID_State" OtherKey="FK_State" Type="SmetaValue" />
      <Association Name="Konkursy_Smeta" Member="Konkursy" ThisKey="FK_Konkurs" OtherKey="ID_Konkurs" Type="Konkursy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SmetaValue" Member="SmetaValue">
    <Type Name="SmetaValue">
      <Column Name="ID_Value" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Bids_SmetaValue" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
      <Association Name="Smeta_SmetaValue" Member="Smeta" ThisKey="FK_State" OtherKey="ID_State" Type="Smeta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SpecialPart" Member="SpecialPart">
    <Type Name="SpecialPart">
      <Column Name="ID_Equipment" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Purchase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Equipment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PercentInProject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PercentNotInProject" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PurchasePlan_SpecialPart" Member="PurchasePlan" ThisKey="FK_Purchase" OtherKey="ID_Purchase" Type="PurchasePlan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TargetIndicators" Member="TargetIndicators">
    <Type Name="TargetIndicators">
      <Column Name="ID_TargetIndicator" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TargetIndicator" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Abb" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Uniqvalue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TargetIndicators_Konkurs_TargetMapingTable" Member="Konkurs_TargetMapingTable" ThisKey="ID_TargetIndicator" OtherKey="FK_Target" Type="Konkurs_TargetMapingTable" />
      <Association Name="TargetIndicators_TargetIndicatorValue" Member="TargetIndicatorValue" ThisKey="ID_TargetIndicator" OtherKey="FK_TargetIndicator" Type="TargetIndicatorValue" />
    </Type>
  </Table>
  <Table Name="dbo.TargetIndicatorValue" Member="TargetIndicatorValue">
    <Type Name="TargetIndicatorValue">
      <Column Name="ID_TargetIndicatorValue" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_TargetIndicator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PurchaseValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FK_Purchase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartValue2015" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EndValue2015" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Value2020" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Bids_TargetIndicatorValue" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
      <Association Name="PurchasePlan_TargetIndicatorValue" Member="PurchasePlan" ThisKey="FK_Purchase" OtherKey="ID_Purchase" Type="PurchasePlan" IsForeignKey="true" />
      <Association Name="TargetIndicators_TargetIndicatorValue" Member="TargetIndicators" ThisKey="FK_TargetIndicator" OtherKey="ID_TargetIndicator" Type="TargetIndicators" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaskResult" Member="TaskResult">
    <Type Name="TaskResult">
      <Column Name="ID_Task" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Task" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Result" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TaskResult_Result" Member="Result1" ThisKey="ID_Task" OtherKey="FK_Task" Type="Result" />
      <Association Name="Bids_TaskResult" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TitleInfo" Member="TitleInfo">
    <Type Name="TitleInfo">
      <Column Name="ID_Information" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PlanStartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PlanEndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TotalBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GrantBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Curator" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IndividualCommand" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Bids_TitleInfo" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User-BidMapingTable]" Member="User_BidMapingTable">
    <Type Name="User_BidMapingTable">
      <Column Name="ID_UserBid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Access" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Bids_User_BidMapingTable" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
      <Association Name="Users_User_BidMapingTable" Member="Users" ThisKey="FK_User" OtherKey="ID_User" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Post" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PlaceofWork" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[E-mail]" Member="E_mail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Function]" Member="Function" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PayPerHour" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Users_Konkursy" Member="Konkursy" ThisKey="ID_User" OtherKey="FK_Curator" Type="Konkursy" />
      <Association Name="Users_User_BidMapingTable" Member="User_BidMapingTable" ThisKey="ID_User" OtherKey="FK_User" Type="User_BidMapingTable" />
    </Type>
  </Table>
</Database>