<?xml version="1.0" encoding="utf-8"?><Database Name="Konkursy" Class="CompetitionDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=РЕМА-ПК\REMAIDEMBUHAT;Initial Catalog=Konkursy;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KonkursyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AutoFilling" Member="AutoFilling">
    <Type Name="AutoFilling">
      <Column Name="ID_Doc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_Konkurs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Page" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Konkursy_AutoFilling" Member="Konkursy" ThisKey="FK_Konkurs" OtherKey="ID_Konkurs" Type="Konkursy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bids" Member="Bids">
    <Type Name="Bids">
      <Column Name="ID_Bid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Konkurs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Coment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Bids_SmetaValue" Member="SmetaValue" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="SmetaValue" />
      <Association Name="Bids_User_BidMapingTable" Member="User_BidMapingTable" ThisKey="ID_Bid" OtherKey="FK_Bid" Type="User_BidMapingTable" />
      <Association Name="Konkursy_Bids" Member="Konkursy" ThisKey="FK_Konkurs" OtherKey="ID_Konkurs" Type="Konkursy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Konkursy" Member="Konkursy">
    <Type Name="Konkursy">
      <Column Name="ID_Konkurs" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FK_Curator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Konkursy_AutoFilling" Member="AutoFilling" ThisKey="ID_Konkurs" OtherKey="FK_Konkurs" Type="AutoFilling" />
      <Association Name="Konkursy_Bids" Member="Bids" ThisKey="ID_Konkurs" OtherKey="FK_Konkurs" Type="Bids" />
      <Association Name="Konkursy_Smeta" Member="Smeta" ThisKey="ID_Konkurs" OtherKey="FK_Konkurs" Type="Smeta" />
      <Association Name="Users_Konkursy" Member="Users" ThisKey="FK_Curator" OtherKey="ID_User" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Smeta" Member="Smeta">
    <Type Name="Smeta">
      <Column Name="ID_State" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name_state" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Type_state" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Uniqvalue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FK_Konkurs" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Smeta_SmetaValue" Member="SmetaValue" ThisKey="ID_State" OtherKey="FK_State" Type="SmetaValue" />
      <Association Name="Konkursy_Smeta" Member="Konkursy" ThisKey="FK_Konkurs" OtherKey="ID_Konkurs" Type="Konkursy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SmetaValue" Member="SmetaValue">
    <Type Name="SmetaValue">
      <Column Name="ID_Value" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Bids_SmetaValue" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
      <Association Name="Smeta_SmetaValue" Member="Smeta" ThisKey="FK_State" OtherKey="ID_State" Type="Smeta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User-BidMapingTable]" Member="User_BidMapingTable">
    <Type Name="User_BidMapingTable">
      <Column Name="[ID_User-Bid]" Member="ID_User_Bid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Bid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Bids_User_BidMapingTable" Member="Bids" ThisKey="FK_Bid" OtherKey="ID_Bid" Type="Bids" IsForeignKey="true" />
      <Association Name="Users_User_BidMapingTable" Member="Users" ThisKey="FK_User" OtherKey="ID_User" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="ID_User" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Post" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PlaceofWork" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[E-mail]" Member="E_mail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[Function]" Member="Function" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PayPerHour" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Users_Konkursy" Member="Konkursy" ThisKey="ID_User" OtherKey="FK_Curator" Type="Konkursy" />
      <Association Name="Users_User_BidMapingTable" Member="User_BidMapingTable" ThisKey="ID_User" OtherKey="FK_User" Type="User_BidMapingTable" />
    </Type>
  </Table>
</Database>