<?xml version="1.0" encoding="utf-8"?><Database Name="ApproveDB" Class="EDMdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=212.110.152.173;Initial Catalog=ApproveDB;Persist Security Info=True;User ID=potapov" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ApproveDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Documents">
      <Column Name="documentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="documentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fk_processVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="documentComment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ProcessVersions_Documents" Member="ProcessVersions" ThisKey="fk_processVersion" OtherKey="processVersionID" Type="ProcessVersions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="struct" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="fk_struct" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="canInitiate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="canCreateTemplate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Users_Participants" Member="Participants" ThisKey="userID" OtherKey="fk_user" Type="Participants" />
      <Association Name="Users_Processes" Member="Processes" ThisKey="userID" OtherKey="fk_initiator" Type="Processes" />
      <Association Name="Users_ProcessTemplate" Member="ProcessTemplate" ThisKey="userID" OtherKey="fk_owner" Type="ProcessTemplate" />
      <Association Name="Users_ProcessTemplateParticipant" Member="ProcessTemplateParticipant" ThisKey="userID" OtherKey="fk_user" Type="ProcessTemplateParticipant" />
      <Association Name="Struct_Users" Member="Struct1" ThisKey="fk_struct" OtherKey="structID" Type="Struct" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentsInStep" Member="DocumentsInStep">
    <Type Name="DocumentsInStep">
      <Column Name="documentsInStepId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="documentName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fk_step" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="documentComment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Steps_DocumentsInStep" Member="Steps" ThisKey="fk_step" OtherKey="stepID" Type="Steps" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmailBots" Member="EmailBots">
    <Type Name="EmailBots">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="smtpName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="port" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="sendOk" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="sendError" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.EmailCopies" Member="EmailCopies">
    <Type Name="EmailCopies">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="emailTo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="emailFrom" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="emailTitle" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="emailContent" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="emailAttachment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="sendDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sendOk" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="errorMessage" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.EmailTemplates" Member="EmailTemplates">
    <Type Name="EmailTemplates">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="emailTitle" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="emailContent" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="comment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Participants" Member="Participants">
    <Type Name="Participants">
      <Column Name="participantID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fk_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_process" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="queue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isNew" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Participants_Steps" Member="Steps" ThisKey="participantID" OtherKey="fk_participent" Type="Steps" />
      <Association Name="Users_Participants" Member="Users" ThisKey="fk_user" OtherKey="userID" Type="Users" IsForeignKey="true" />
      <Association Name="Processes_Participants" Member="Processes" ThisKey="fk_process" OtherKey="processID" Type="Processes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Processes" Member="Processes">
    <Type Name="Processes">
      <Column Name="processID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fk_initiator" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="startDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="endDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="endComment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Processes_Participants" Member="Participants" ThisKey="processID" OtherKey="fk_process" Type="Participants" />
      <Association Name="Processes_ProcessVersions" Member="ProcessVersions" ThisKey="processID" OtherKey="fk_process" Type="ProcessVersions" />
      <Association Name="Users_Processes" Member="Users" ThisKey="fk_initiator" OtherKey="userID" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProcessTemplate" Member="ProcessTemplate">
    <Type Name="ProcessTemplate">
      <Column Name="processTemplateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fk_owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="content_" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ProcessTemplate_ProcessTemplateParticipant" Member="ProcessTemplateParticipant" ThisKey="processTemplateId" OtherKey="fk_template" Type="ProcessTemplateParticipant" />
      <Association Name="Users_ProcessTemplate" Member="Users" ThisKey="fk_owner" OtherKey="userID" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProcessTemplateParticipant" Member="ProcessTemplateParticipant">
    <Type Name="ProcessTemplateParticipant">
      <Column Name="processTemplateParticipantId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fk_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="queue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="endDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fk_template" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ProcessTemplate_ProcessTemplateParticipant" Member="ProcessTemplate" ThisKey="fk_template" OtherKey="processTemplateId" Type="ProcessTemplate" IsForeignKey="true" />
      <Association Name="Users_ProcessTemplateParticipant" Member="Users" ThisKey="fk_user" OtherKey="userID" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProcessVersions" Member="ProcessVersions">
    <Type Name="ProcessVersions">
      <Column Name="processVersionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fk_process" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="ProcessVersions_Documents" Member="Documents" ThisKey="processVersionID" OtherKey="fk_processVersion" Type="Documents" />
      <Association Name="ProcessVersions_Steps" Member="Steps" ThisKey="processVersionID" OtherKey="fk_processVersion" Type="Steps" />
      <Association Name="Processes_ProcessVersions" Member="Processes" ThisKey="fk_process" OtherKey="processID" Type="Processes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Steps" Member="Steps">
    <Type Name="Steps">
      <Column Name="stepID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fk_processVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_participent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="stepResult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Steps_DocumentsInStep" Member="DocumentsInStep" ThisKey="stepID" OtherKey="fk_step" Type="DocumentsInStep" />
      <Association Name="Participants_Steps" Member="Participants" ThisKey="fk_participent" OtherKey="participantID" Type="Participants" IsForeignKey="true" />
      <Association Name="ProcessVersions_Steps" Member="ProcessVersions" ThisKey="fk_processVersion" OtherKey="processVersionID" Type="ProcessVersions" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Struct" Member="Struct">
    <Type Name="Struct">
      <Column Name="structID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fk_parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Struct_Users" Member="Users" ThisKey="structID" OtherKey="fk_struct" Type="Users" />
      <Association Name="Struct_Struct" Member="Struct2" ThisKey="structID" OtherKey="fk_parent" Type="Struct" />
      <Association Name="Struct_Struct" Member="Struct1" ThisKey="fk_parent" OtherKey="structID" Type="Struct" IsForeignKey="true" />
    </Type>
  </Table>
</Database>