<?xml version="1.0" encoding="utf-8"?><Database Name="ZakupkaDB" Class="ZakupkaDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=212.110.152.173;Initial Catalog=ZakupkaDB;Persist Security Info=True;User ID=potapov" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ZakupkaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ContractProjectMappingTable" Member="ContractProjectMappingTable">
    <Type Name="ContractProjectMappingTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="fk_project" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_contract" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contracts_ContractProjectMappingTable" Member="Contracts" ThisKey="fk_contract" OtherKey="contractID" Type="Contracts" IsForeignKey="true" />
      <Association Name="Projects_ContractProjectMappingTable" Member="Projects" ThisKey="fk_project" OtherKey="projectID" Type="Projects" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contracts" Member="Contracts">
    <Type Name="Contracts">
      <Column Name="contractID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Contracts_ContractProjectMappingTable" Member="ContractProjectMappingTable" ThisKey="contractID" OtherKey="fk_contract" Type="ContractProjectMappingTable" />
      <Association Name="Contracts_CollectedValues" Member="CollectedValues" ThisKey="contractID" OtherKey="fk_contract" Type="CollectedValues" />
    </Type>
  </Table>
  <Table Name="dbo.CostClassTable" Member="CostClassTable">
    <Type Name="CostClassTable">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Events">
      <Column Name="eventID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fk_mainevent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Events_ProjectEventMappingTable" Member="ProjectEventMappingTable" ThisKey="eventID" OtherKey="fk_event" Type="ProjectEventMappingTable" />
      <Association Name="Events_CollectedValues" Member="CollectedValues" ThisKey="eventID" OtherKey="fk_event" Type="CollectedValues" />
      <Association Name="Events_ProjectsValues" Member="ProjectsValues" ThisKey="eventID" OtherKey="fk_event" Type="ProjectsValues" />
      <Association Name="MainEvent_Events" Member="MainEvent" ThisKey="fk_mainevent" OtherKey="ID" Type="MainEvent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KOSGUtable" Member="KOSGUtable">
    <Type Name="KOSGUtable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Class" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KOSGUtable_CollectedValues" Member="CollectedValues" ThisKey="ID" OtherKey="fk_kosgu" Type="CollectedValues" />
      <Association Name="KOSGUtable_ProjectsValues" Member="ProjectsValues" ThisKey="ID" OtherKey="fk_kosgu" Type="ProjectsValues" />
    </Type>
  </Table>
  <Table Name="dbo.MainEvent" Member="MainEvent">
    <Type Name="MainEvent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MainEvent" Member="MainEvent1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MainEvent_Events" Member="Events" ThisKey="ID" OtherKey="fk_mainevent" Type="Events" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectEventMappingTable" Member="ProjectEventMappingTable">
    <Type Name="ProjectEventMappingTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_event" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_project" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Events_ProjectEventMappingTable" Member="Events" ThisKey="fk_event" OtherKey="eventID" Type="Events" IsForeignKey="true" />
      <Association Name="Projects_ProjectEventMappingTable" Member="Projects" ThisKey="fk_project" OtherKey="projectID" Type="Projects" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Projects">
      <Column Name="projectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Projects_ContractProjectMappingTable" Member="ContractProjectMappingTable" ThisKey="projectID" OtherKey="fk_project" Type="ContractProjectMappingTable" />
      <Association Name="Projects_ProjectEventMappingTable" Member="ProjectEventMappingTable" ThisKey="projectID" OtherKey="fk_project" Type="ProjectEventMappingTable" />
      <Association Name="Projects_CollectedValues" Member="CollectedValues" ThisKey="projectID" OtherKey="fk_project" Type="CollectedValues" />
      <Association Name="Projects_ProjectsValues" Member="ProjectsValues" ThisKey="projectID" OtherKey="fk_project" Type="ProjectsValues" />
    </Type>
  </Table>
  <Table Name="dbo.StructTable" Member="StructTable">
    <Type Name="StructTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="struct" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CollectedValues" Member="CollectedValues">
    <Type Name="CollectedValues">
      <Column Name="collectedFieldID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="fk_field" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_contract" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_project" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_event" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_kosgu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Contracts_CollectedValues" Member="Contracts" ThisKey="fk_contract" OtherKey="contractID" Type="Contracts" IsForeignKey="true" />
      <Association Name="Events_CollectedValues" Member="Events" ThisKey="fk_event" OtherKey="eventID" Type="Events" IsForeignKey="true" />
      <Association Name="KOSGUtable_CollectedValues" Member="KOSGUtable" ThisKey="fk_kosgu" OtherKey="ID" Type="KOSGUtable" IsForeignKey="true" />
      <Association Name="Projects_CollectedValues" Member="Projects" ThisKey="fk_project" OtherKey="projectID" Type="Projects" IsForeignKey="true" />
      <Association Name="Fields_CollectedValues" Member="Fields" ThisKey="fk_field" OtherKey="filedID" Type="Fields" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectsValues" Member="ProjectsValues">
    <Type Name="ProjectsValues">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_field" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_project" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_kosgu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="value" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="fk_event" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Events_ProjectsValues" Member="Events" ThisKey="fk_event" OtherKey="eventID" Type="Events" IsForeignKey="true" />
      <Association Name="KOSGUtable_ProjectsValues" Member="KOSGUtable" ThisKey="fk_kosgu" OtherKey="ID" Type="KOSGUtable" IsForeignKey="true" />
      <Association Name="Projects_ProjectsValues" Member="Projects" ThisKey="fk_project" OtherKey="projectID" Type="Projects" IsForeignKey="true" />
      <Association Name="Fields_ProjectsValues" Member="Fields" ThisKey="fk_field" OtherKey="filedID" Type="Fields" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fields" Member="Fields">
    <Type Name="Fields">
      <Column Name="filedID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="commonfield" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="line" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="col" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="step" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sumby" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="staticvalue" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="engname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Fields_CollectedValues" Member="CollectedValues" ThisKey="filedID" OtherKey="fk_field" Type="CollectedValues" />
      <Association Name="Fields_ProjectsValues" Member="ProjectsValues" ThisKey="filedID" OtherKey="fk_field" Type="ProjectsValues" />
      <Association Name="Fields_ViewField" Member="ViewField" ThisKey="filedID" OtherKey="fk_field" Type="ViewField" />
    </Type>
  </Table>
  <Table Name="dbo.ViewField" Member="ViewField">
    <Type Name="ViewField">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="viewtype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_field" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="orderby" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="byproject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Fields_ViewField" Member="Fields" ThisKey="fk_field" OtherKey="filedID" Type="Fields" IsForeignKey="true" />
    </Type>
  </Table>
</Database>