<?xml version="1.0" encoding="utf-8"?><Database Name="Release_" Class="PersonalPagesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=212.110.152.173;Initial Catalog=Release_;User ID=potapov" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MainDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FirstLevelSubdivisionTable" Member="FirstLevelSubdivisionTable">
    <Type Name="FirstLevelSubdivisionTable">
      <Column Name="FirstLevelSubdivisionTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FK_ZeroLevelSubvisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AbbRu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="FirstLevelSubdivisionTable_SecondLevelSubdivisionTable" Member="SecondLevelSubdivisionTable" ThisKey="FirstLevelSubdivisionTableID" OtherKey="FK_FirstLevelSubdivisionTable" Type="SecondLevelSubdivisionTable" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroupTable" Member="UserGroupTable">
    <Type Name="UserGroupTable">
      <Column Name="UserGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserGroupName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="URLtoGroupMain" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AutoLogin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Fk_ProjectsTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="UserGroupTable_UsersAndUserGroupMappingTable1" Member="UsersAndUserGroupMappingTable1" ThisKey="UserGroupID" OtherKey="FK_GroupTable" Type="UsersAndUserGroupMappingTable1" />
      <Association Name="UserGroupTable_ApplictionTypes" Member="ApplictionTypes" ThisKey="UserGroupID" OtherKey="FK_UserGroupTable" Type="ApplictionTypes" />
      <Association Name="UserGroupTable_UsersAndUserGroupMappingTable" Member="UsersAndUserGroupMappingTable" ThisKey="UserGroupID" OtherKey="FK_GroupTable" Type="UsersAndUserGroupMappingTable" />
      <Association Name="Projects_UserGroupTable" Member="Projects" ThisKey="Fk_ProjectsTable" OtherKey="Id" Type="Projects" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserDataChangeHistory" Member="UserDataChangeHistory">
    <Type Name="UserDataChangeHistory">
      <Column Name="UserChangeDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ID_Param_ToChange" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OldValue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NewValue" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="UsersTable_UserDataChangeHistory" Member="UsersTable" ThisKey="FK_User" OtherKey="UsersTableID" Type="UsersTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersAndUserGroupMappingTable" Member="UsersAndUserGroupMappingTable1">
    <Type Name="UsersAndUserGroupMappingTable1">
      <Column Name="UserAndGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_UserTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_GroupTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="UserGroupTable_UsersAndUserGroupMappingTable1" Member="UserGroupTable" ThisKey="FK_GroupTable" OtherKey="UserGroupID" Type="UserGroupTable" IsForeignKey="true" />
      <Association Name="UsersTable_UsersAndUserGroupMappingTable1" Member="UsersTable" ThisKey="FK_UserTable" OtherKey="UsersTableID" Type="UsersTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThirdLevelSubdivisionTable" Member="ThirdLevelSubdivisionTable">
    <Type Name="ThirdLevelSubdivisionTable">
      <Column Name="ThirdLevelSubdivisionTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FK_SecondLevelSubdivisionTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SecondLevelSubdivisionTable_ThirdLevelSubdivisionTable" Member="SecondLevelSubdivisionTable" ThisKey="FK_SecondLevelSubdivisionTable" OtherKey="SecondLevelSubdivisionTableID" Type="SecondLevelSubdivisionTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SecondLevelSubdivisionTable" Member="SecondLevelSubdivisionTable">
    <Type Name="SecondLevelSubdivisionTable">
      <Column Name="SecondLevelSubdivisionTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="FK_FirstLevelSubdivisionTable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SecondLevelSubdivisionTable_ThirdLevelSubdivisionTable" Member="ThirdLevelSubdivisionTable" ThisKey="SecondLevelSubdivisionTableID" OtherKey="FK_SecondLevelSubdivisionTable" Type="ThirdLevelSubdivisionTable" />
      <Association Name="SecondLevelSubdivisionTable_StudentGroupsTable" Member="StudentGroupsTable" ThisKey="SecondLevelSubdivisionTableID" OtherKey="FK_SecondLevel" Type="StudentGroupsTable" />
      <Association Name="FirstLevelSubdivisionTable_SecondLevelSubdivisionTable" Member="FirstLevelSubdivisionTable" ThisKey="FK_FirstLevelSubdivisionTable" OtherKey="FirstLevelSubdivisionTableID" Type="FirstLevelSubdivisionTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ManualTable" Member="ManualTable">
    <Type Name="ManualTable">
      <Column Name="ManualID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ManualName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ManualLink" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Aplications" Member="Aplications">
    <Type Name="Aplications">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FK_ApplicationType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_UserAdd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TelephoneNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FileURL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ApplictionTypes_Aplications" Member="ApplictionTypes" ThisKey="FK_ApplicationType" OtherKey="ID" Type="ApplictionTypes" IsForeignKey="true" />
      <Association Name="UsersTable_Aplications" Member="UsersTable" ThisKey="FK_UserAdd" OtherKey="UsersTableID" Type="UsersTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplictionTypes" Member="ApplictionTypes">
    <Type Name="ApplictionTypes">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ApplicationType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FK_UserGroupTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ApplictionTypes_Aplications" Member="Aplications" ThisKey="ID" OtherKey="FK_ApplicationType" Type="Aplications" />
      <Association Name="UserGroupTable_ApplictionTypes" Member="UserGroupTable" ThisKey="FK_UserGroupTable" OtherKey="UserGroupID" Type="UserGroupTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubdomainRedirectAutologinTable" Member="SubdomainRedirectAutologinTable">
    <Type Name="SubdomainRedirectAutologinTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PassCode" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UsersAndUserGroupMappingTable" Member="UsersAndUserGroupMappingTable">
    <Type Name="UsersAndUserGroupMappingTable">
      <Column Name="UserAndGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_UserTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_GroupTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Confirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="UserGroupTable_UsersAndUserGroupMappingTable" Member="UserGroupTable" ThisKey="FK_GroupTable" OtherKey="UserGroupID" Type="UserGroupTable" IsForeignKey="true" />
      <Association Name="UsersTable_UsersAndUserGroupMappingTable" Member="UsersTable" ThisKey="FK_UserTable" OtherKey="UsersTableID" Type="UsersTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TypeOfWritingFIO" Member="TypeOfWritingFIO">
    <Type Name="TypeOfWritingFIO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_UserTableID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FIO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="UsersTable_TypeOfWritingFIO" Member="UsersTable" ThisKey="FK_UserTableID" OtherKey="UsersTableID" Type="UsersTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersTable" Member="UsersTable">
    <Type Name="UsersTable">
      <Column Name="UsersTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FK_FirstLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_SecondLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ThirdLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_FourthLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_FifthLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ZeroLevelSubdivisionTable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PassCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Confirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Patronimyc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AcademicDegree" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AcademicRank" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Data_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Kurs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YearEnter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_Specialization" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_StudentGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UsersTable_UserDataChangeHistory" Member="UserDataChangeHistory" ThisKey="UsersTableID" OtherKey="FK_User" Type="UserDataChangeHistory" />
      <Association Name="UsersTable_UsersAndUserGroupMappingTable1" Member="UsersAndUserGroupMappingTable1" ThisKey="UsersTableID" OtherKey="FK_UserTable" Type="UsersAndUserGroupMappingTable1" />
      <Association Name="UsersTable_Aplications" Member="Aplications" ThisKey="UsersTableID" OtherKey="FK_UserAdd" Type="Aplications" />
      <Association Name="UsersTable_UsersAndUserGroupMappingTable" Member="UsersAndUserGroupMappingTable" ThisKey="UsersTableID" OtherKey="FK_UserTable" Type="UsersAndUserGroupMappingTable" />
      <Association Name="UsersTable_TypeOfWritingFIO" Member="TypeOfWritingFIO" ThisKey="UsersTableID" OtherKey="FK_UserTableID" Type="TypeOfWritingFIO" />
      <Association Name="StudentGroupsTable_UsersTable" Member="StudentGroupsTable" ThisKey="FK_StudentGroup" OtherKey="ID" Type="StudentGroupsTable" IsForeignKey="true" />
      <Association Name="SpecializationTable_UsersTable" Member="SpecializationTable" ThisKey="FK_Specialization" OtherKey="SpecializationTableID" Type="SpecializationTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Projects">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ProjectName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreateButton" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Projects_UserGroupTable" Member="UserGroupTable" ThisKey="Id" OtherKey="Fk_ProjectsTable" Type="UserGroupTable" />
    </Type>
  </Table>
  <Table Name="dbo.StudentGroupsTable" Member="StudentGroupsTable">
    <Type Name="StudentGroupsTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FK_SecondLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="StudentGroupsTable_UsersTable" Member="UsersTable" ThisKey="ID" OtherKey="FK_StudentGroup" Type="UsersTable" />
      <Association Name="SecondLevelSubdivisionTable_StudentGroupsTable" Member="SecondLevelSubdivisionTable" ThisKey="FK_SecondLevel" OtherKey="SecondLevelSubdivisionTableID" Type="SecondLevelSubdivisionTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SpecializationTable" Member="SpecializationTable">
    <Type Name="SpecializationTable">
      <Column Name="SpecializationTableID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="SpecializationNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FK_FieldOfExpertise" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SpecializationTable_UsersTable" Member="UsersTable" ThisKey="SpecializationTableID" OtherKey="FK_Specialization" Type="UsersTable" />
    </Type>
  </Table>
</Database>